### ISSUE TITLE
Dragonflight TODO list

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#3727]
### DONE ###
* [x] Dynamic Groups Improvements: Classes will have a lot more "optional" spells in DF, the best way to lay that out is argueably dynamic groups. We might need more layout options, and dynamic groups sort/layout too often. => bunch of tickets
* [x] Evoker's essence => Power trigger done. As it's own trigger with progress per essence waiting for more stable API. And that stable api is missing even 4 days before the release. I guess they don't care enough.
* [x] Styling Inspirations from new default UI => https://github.com/WeakAuras/WeakAuras2/issues/4054
* [x] Show/Magnetic to the UI Edit grid (?) = https://github.com/WeakAuras/WeakAuras2/issues/4053
* [x] Rewrite BT2 again: https://wowpedia.fandom.com/wiki/Patch_10.0.0/API_changes#Unit_Aura_Changes => https://github.com/WeakAuras/WeakAuras2/issues/4052
* [x] UnitTokenFromGUID. We actually have no use for that. We don't really use guids much, the combat log trigger could mabye use it to fetch more information. The other place where we use guids a lot is in the buff trigger's multi tracking. But the main purpose of that code is to also augment match datas if we later get a unit id for a guid and that means we need the tracking code anyway.
* [x] Stop Motion: Add FlipBook textures ?
* [x] C_TooltipInfo  ?
* [x] Test and improve conversion from existing settings. (Talent, Covenant, BT1, BT2)
* [x] FontStrings in 10.0 have gained Get/SetRotation APIs now (Postponed, the api is too buggy atm)
* [x] MajorFaction support for Reputation trigger (renown)
* [x] Enable Swipe by default for Icons (That'll break some very old auras, but it's been long enough I think)
* [x] Talent Known trigger needs a rework
* [x] Reenable SetTransform via CreateVector3D, see: https://discord.com/channels/327414731654692866/1014994401644269670/1023663373382058014
* [x] Revert https://github.com/WeakAuras/WeakAuras2/commit/1522aafdaeb819b12260def41415da694b3465dd and use new API instead.
* [x] Cast Trigger: Empower  => need to think about automated ticks placement
* [x] Adjust to new talent system => widget still need to be looked at for optimization, like not create frame for all buttons if not open, check if frames are correctly released when switching tab
* [x] Remove BT1
* [x] Remove covenant load option
* [x] Protect WeakAurasSaved and introduce a supported mechanism for saving data
* [x] Clean up WeakAuras table some more
* [x] Warn about WeakAuras.region usage
* [x] Remove GetLegendariesBonusIds
* [x] Deprecate sending all events to custom triggers, keep same behaviour for existing auras, but add a "OPTIONS_CLOSE"? event for new auras.
* [x] Don't create all regions on login, make most region creation lazy

**Comment by mrbuds** [comment]
I'm (slowly) working on an ace3 widget to replace the dropdown with a mini talent window, it will need a dedicated version for each extension

**Comment by mrbuds** [comment]
Cast trigger has to use new EMPOWER api, and ideally Tick subregions should be able to use it without custom code

**Comment by mrbuds** [comment]
Not TODO, but i see an increase in animations usage & mask textures for castbars and other ui elements, so i expect feature requests to be able to mimic what wow ui does

**Comment by InfusOnWoW** [comment]
All good points! And yeah we should take a look at what blizzard does and add sub elements if possible.

**Comment by mrbuds** [comment]
Reputation trigger => check changes made to framexml/reputationframe.lua and framexml/reputationbar.lua with new MajorFaction stuff

**Comment by seanpeters86** [comment]
>  Dynamic Groups Improvements: Classes will have a lot more "optional" spells in DF, the best way to lay that out is argueably dynamic groups. We might need more layout options, and dynamic groups sort/layout too often.

Just a comment on this, it would make my life much easier if i could put groups into a dynamic group and layout my auras that way. Thinking of basically having a dynamic group per "row" in my sets that i can set to a static layout and have groups for each talent. 

![image](https://user-images.githubusercontent.com/10604059/187262631-1c5217be-d38d-4419-ae41-457169facffb.png)
Taking the following image, if i wanted to do this in a dynamic group it would look something like this: 

Row 2 (Dynamic Group):
- Shadow Word: Death (Group)
  - SW:D - CD
  - SW:D - Debuff on Target for Death and Madness
- Mindgames (Group)
  - Mindgames - CD
  - Mindgames - Debuff active
- Power Infusion (Group)
  - Power Infusion - CD
  - Power Infusion - Active 
... so on and so on such that I can add more than 6 "groups" here and just show the top 6 in the actual row based on talents. This can be accomplished in other ways and i could definitely squash a lot of these into just one aura but having groups would at least help me organize things better/make it simpler to find things. 

This is just my 2 cents, if you'd prefer i can move this comment to a new issue if you think its valid.

**Comment by Stanzilla** [comment]
> > Dynamic Groups Improvements: Classes will have a lot more "optional" spells in DF, the best way to lay that out is argueably dynamic groups. We might need more layout options, and dynamic groups sort/layout too often.
> 
> Just a comment on this, it would make my life much easier if i could put groups into a dynamic group and layout my auras that way. Thinking of basically having a dynamic group per "row" in my sets that i can set to a static layout and have groups for each talent.
> 
> ![image](https://user-images.githubusercontent.com/10604059/187262631-1c5217be-d38d-4419-ae41-457169facffb.png) Taking the following image, if i wanted to do this in a dynamic group it would look something like this:
> 
> Row 2 (Dynamic Group):
> 
> * Shadow Word: Death (Group)
>   
>   * SW:D - CD
>   * SW:D - Debuff on Target for Death and Madness
> * Mindgames (Group)
>   
>   * Mindgames - CD
>   * Mindgames - Debuff active
> * Power Infusion (Group)
>   
>   * Power Infusion - CD
>   * Power Infusion - Active
> 
> ... so on and so on such that I can add more than 6 "groups" here and just show the top 6 in the actual row based on talents. This can be accomplished in other ways and i could definitely squash a lot of these into just one aura but having groups would at least help me organize things better/make it simpler to find things.
> 
> This is just my 2 cents, if you'd prefer i can move this comment to a new issue if you think its valid.

new issue please!

**Comment by mrbuds** [comment]
Evoker's essence may needs it's own trigger like DK Rune, or rename DK rune and support essences in same trigger
I have not look how their internals works yet

**Comment by InfusOnWoW** [comment]
Probably its own trigger, the dk trigger is a rather complex beast. But let me add it to the todo list.

**Comment by InfusOnWoW** [comment]
All done or distributed to its own triggers.
